services:
  postgres:
    image: postgres:15
    container_name: cep-postgres
    restart: always
    environment:
      POSTGRES_DB: cepdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  wiremock:
    image: wiremock/wiremock:3.13.2
    container_name: cep-wiremock
    ports:
      - "8081:8080"
    volumes:
      - ./mocks:/home/wiremock
    command: [ "--verbose" ]

volumes:
  postgres_data:

